### ISSUE TITLE
В РО інколи деякий товар позначається, як не замовлений, але при цьому він замовлений

### ISSUE THREAD

**Issue by ralfeus** [ralfeus/order#62]
```
[2021-01-21 13:55:29,257: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]:  Open quick order
[2021-01-21 13:55:30,679: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Adding products
[2021-01-21 13:55:33,458: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 004240
[2021-01-21 13:55:35,337: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 000184
[2021-01-21 13:55:37,171: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 4008
[2021-01-21 13:55:39,025: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 004004
[2021-01-21 13:55:40,868: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 248
[2021-01-21 13:55:42,807: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 238
[2021-01-21 13:55:44,625: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 1812
[2021-01-21 13:55:46,476: DEBUG/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Added product 2434
[2021-01-21 13:55:52,928: ERROR/ForkPoolWorker-2] app.purchase.jobs.post_purchase_orders[5adc3a73-e8f4-4eb0-a11e-665006e17b14]: Couldn't add product 000150
Traceback (most recent call last):
  File "/var/www/order/app/purchase/models/vendors/atomy_quick.py", line 114, in __add_products
    while product_code_input.get_attribute('value') == op.product_id:
  File "/usr/virtualfish/order/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 139, in get_attribute
    attributeValue = self.parent.execute_script(
  File "/usr/virtualfish/order/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/usr/virtualfish/order/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/virtualfish/order/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 한번에 최대 10개 품목까지 상품을 구매할 수 있습니다.
Message: unexpected alert open: {Alert text : 한번에 최대 10개 품목까지 상품을 구매할 수 있습니다.}
  (Session info: headless chrome=87.0.4280.88)
```

**Comment by ralfeus** [comment]
Схоже, що останні зміни допомогли (додаткова перевірка всіх запощених товарів)
